Cleanup options/arguments

diff --git a/bin/linode-create b/bin/linode-create
--- a/bin/linode-create
+++ b/bin/linode-create
@@ -20,27 +20,27 @@ Usage: $PROGRAM [OPTIONS] LABEL
 
 Create linode instance.
 
-Required arguments:
-  LABEL                  Instance label
+Arguments:
+  LABEL                    Instance label
 
-Optional arguments:
-  -k, --token=TOKEN      API token
-  -i, --image=IMAGE      Linode image (default: $LINODE_IMAGE)
-  -r, --region=REGION    Linode region (default: $LINODE_REGION)
-  -t, --type=TYPE        Linode type (default: $LINODE_TYPE)
-  -o, --output=PATH      Path to output result as shell variables
-  -q, --quiet            Suppress output
-  -h, --help             This help text
+Options:
+  -k, --api-token=TOKEN    API token (required)
+  -i, --image=IMAGE        Linode image (default: $LINODE_IMAGE)
+  -r, --region=REGION      Linode region (default: $LINODE_REGION)
+  -t, --type=TYPE          Linode type (default: $LINODE_TYPE)
+  -o, --output=PATH        Path to output result as shell variables
+  -q, --quiet              Suppress output
+  -h, --help               This help text
 
-Enviroment variable mappings:
-  LINODE_API_TOKEN       --token
-  LINODE_IMAGE           --image
-  LINODE_REGION          --region
-  LINODE_TYPE            --type
-  CURL_EXEC              Path to curl
-  JQ_EXEC                Path to jq
-  LINODE_API_EXEC        Path to linode-api
-  LINODE_QUERY_EXEC      Path to linode-query
+Enviroment variables:
+  LINODE_API_TOKEN         See --api-token
+  LINODE_IMAGE             See --image
+  LINODE_REGION            See --region
+  LINODE_TYPE              See --type
+  CURL_EXEC                Path to curl
+  JQ_EXEC                  Path to jq
+  LINODE_API_EXEC          Path to linode-api
+  LINODE_QUERY_EXEC        Path to linode-query
 EOF
 }
 
@@ -77,7 +77,7 @@ while [ $# -gt 0 ]; do
   ARG="$1"
   shift
   case "$ARG" in
-  -k | --token)
+  -k | --api-token)
     LINODE_API_TOKEN="$1"
     shift
     ;;
@@ -105,15 +105,12 @@ while [ $# -gt 0 ]; do
     exit 0
     ;;
   --)
-    while [ $# -gt 0 ]; do
-      ARG="$1"
-      if [ -z "$LINODE_LABEL" ]; then
-        LINODE_LABEL="$ARG"
-      else
-        error "unexpected argument '$ARG'"
-      fi
+    if [ $# -eq 1 ]; then
+      LINODE_LABEL="$1"
       shift
-    done
+    elif [ $# -gt 1 ]; then
+      error "unexpected argument '$2'"
+    fi
     ;;
   *)
     error "unexpected option '$ARG'"
@@ -121,32 +118,31 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-[ -z "${LINODE_LABEL:-}" ] && error "missing LABEL"
-[ -z "${LINODE_API_TOKEN:-}" ] && error "missing TOKEN"
+[ -z "$LINODE_LABEL" ] && error "missing LABEL"
+[ -z "$LINODE_API_TOKEN" ] && error "missing --api-token=TOKEN"
 
-which "$JQ_EXEC" >/dev/null || error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
+which "$JQ_EXEC" >/dev/null || error "jq not found"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not found"
 
 if [ "$OUTPUT_PATH" = - ]; then
   OUTPUT_PATH=/dev/stdout
   QUIET=1
 fi
 
-export LINODE_API_TOKEN
-
 if [ -n "$QUIET" ]; then
-  QUIET_ARG=-q
+  QUIET_ARG=q
 else
   QUIET_ARG=
 fi
+
+export LINODE_API_TOKEN
 
 tmp="$(mktemp)"
 
 trap 'rm -f -- "$tmp"' EXIT
 
 set +e
-# shellcheck disable=SC2086
-linode_query $QUIET_ARG -o "$tmp" "$LINODE_LABEL"
+linode_query "-${QUIET_ARG}o" "$tmp" "$LINODE_LABEL"
 exitcode=$?
 set -e
 
diff --git a/bin/linode-delete b/bin/linode-delete
--- a/bin/linode-delete
+++ b/bin/linode-delete
@@ -17,21 +17,21 @@ Usage: $PROGRAM [OPTIONS] LABEL
 
 Delete linode instance.
 
-Required arguments:
-  LABEL                Instance label
+Arguments:
+  LABEL                    Instance label
 
-Optional arguments:
-  -k, --token=TOKEN    API token
-  -o, --output=PATH    Path to output result as shell variables
-  -q, --quiet          Suppress output
-  -h, --help           This help text
+Options:
+  -k, --api-token=TOKEN    API token (required)
+  -o, --output=PATH        Path to output result as shell variables
+  -q, --quiet              Suppress output
+  -h, --help               This help text
 
-Enviroment variable mappings:
-  LINODE_API_TOKEN     --token
-  CURL_EXEC            Path to curl
-  JQ_EXEC              Path to jq
-  LINODE_API_EXEC      Path to linode-api
-  LINODE_QUERY_EXEC    Path to linode-query
+Enviroment variables:
+  LINODE_API_TOKEN         See --token
+  CURL_EXEC                Path to curl
+  JQ_EXEC                  Path to jq
+  LINODE_API_EXEC          Path to linode-api
+  LINODE_QUERY_EXEC        Path to linode-query
 EOF
 }
 
@@ -59,7 +59,7 @@ out() {
 
 opts="$(
   getopt -n "$PROGRAM" -o k:o:qh \
-    -l token:,output:,quiet,help -- "$@"
+    -l api-token:,output:,quiet,help -- "$@"
 )" || error
 # shellcheck disable=SC2086
 eval set -- $opts
@@ -68,7 +68,7 @@ while [ $# -gt 0 ]; do
   ARG="$1"
   shift
   case "$ARG" in
-  -k | --token)
+  -k | --api-token)
     LINODE_API_TOKEN="$1"
     shift
     ;;
@@ -84,15 +84,12 @@ while [ $# -gt 0 ]; do
     exit 0
     ;;
   --)
-    while [ $# -gt 0 ]; do
-      ARG="$1"
-      if [ -z "$LINODE_LABEL" ]; then
-        LINODE_LABEL="$ARG"
-      else
-        error "unexpected argument '$ARG'"
-      fi
+    if [ $# -eq 1 ]; then
+      LINODE_LABEL="$1"
       shift
-    done
+    elif [ $# -gt 1 ]; then
+      error "unexpected argument '$2'"
+    fi
     ;;
   *)
     error "unexpected option '$ARG'"
@@ -100,11 +97,11 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-[ -z "${LINODE_LABEL:-}" ] && error "missing LABEL"
-[ -z "${LINODE_API_TOKEN:-}" ] && error "missing TOKEN"
+[ -z "$LINODE_LABEL" ] && error "missing LABEL"
+[ -z "$LINODE_API_TOKEN" ] && error "missing --api-token=TOKEN"
 
-which "$JQ_EXEC" >/dev/null || error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
+which "$JQ_EXEC" >/dev/null || error "jq not found"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not found"
 
 if [ "$OUTPUT_PATH" = - ]; then
   OUTPUT_PATH=/dev/stdout
diff --git a/bin/linode-dns b/bin/linode-dns
--- a/bin/linode-dns
+++ b/bin/linode-dns
@@ -23,23 +23,21 @@ If IPV4 / IPV6 is not specified or blank, then that record is shown.
 If IPV4 / IPV6 is a single dot '.', then that record is deleted.
 If NAME is not specified or blank, then the root records will be shown/updated.
 
-Required arguments:
-  -d, --domain=DOMAIN    Domain name
-  -n, --name=NAME        Domain record name
+Options:
+  -d, --domain=DOMAIN      Domain name (required)
+  -n, --name=NAME          Domain record name (required)
+  -k, --api-token=TOKEN    API token (required)
+  -4, --ipv4=IPV4          Target IPv4 address
+  -6, --ipv6=IPV6          Target IPv6 address
+  -t, --ttl=TTL            Time-to-live (TTL) in seconds
+  -q, --quiet              Suppress output
+  -h, --help               This help text
 
-Optional arguments:
-  -k, --token=TOKEN      API token
-  -4, --ipv4=IPV4        Target IPv4 address
-  -6, --ipv6=IPV6        Target IPv6 address
-  -t, --ttl=TTL          Time-to-live (TTL) in seconds
-  -q, --quiet            Suppress output
-  -h, --help             This help text
-
-Enviroment variable mappings:
-  LINODE_API_TOKEN       --token
-  CURL_EXEC              Path to curl
-  JQ_EXEC                Path to jq
-  LINODE_API_EXEC        Path to linode-api
+Enviroment variables:
+  LINODE_API_TOKEN         See --token
+  CURL_EXEC                Path to curl
+  JQ_EXEC                  Path to jq
+  LINODE_API_EXEC          Path to linode-api
 
 LIMITATION: Only one IPv4 (A) / IPv6 (AAAA) record can be specified per NAME.
 EOF
@@ -80,7 +78,7 @@ out() {
 
 opts="$(
   getopt -n "$PROGRAM" -o k:d:n:4:6:t:h \
-    -l token:,domain:,name:,ipv4:,ipv6:,ttl:,help -- "$@"
+    -l api-token:,domain:,name:,ipv4:,ipv6:,ttl:,help -- "$@"
 )" || error
 # shellcheck disable=SC2086
 eval set -- $opts
@@ -89,7 +87,7 @@ while [ $# -gt 0 ]; do
   ARG="$1"
   shift
   case "$ARG" in
-  -k | --token)
+  -k | --api-token)
     LINODE_API_TOKEN="$1"
     shift
     ;;
@@ -121,18 +119,20 @@ while [ $# -gt 0 ]; do
     usage
     exit 0
     ;;
-  --) ;;
+  --)
+    [ $# -gt 0 ] && error "unexpected argument '$1'"
+    ;;
   *)
     error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "$LINODE_API_TOKEN" ] && error "missing TOKEN"
-[ -z "$LINODE_DOMAIN" ] && error "missing DOMAIN"
+[ -z "$LINODE_API_TOKEN" ] && error "missing --api-token=TOKEN"
+[ -z "$LINODE_DOMAIN" ] && error "missing --domain=DOMAIN"
 
-which "$JQ_EXEC" >/dev/null || error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
+which "$JQ_EXEC" >/dev/null || error "jq not found"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not found"
 
 if [ -n "$LINODE_RECORD_NAME" ]; then
   LINODE_RECORD_FQDN="$LINODE_RECORD_NAME.$LINODE_DOMAIN"
