Cleanup

diff --git a/bin/linode-api b/bin/linode-api
--- a/bin/linode-api
+++ b/bin/linode-api
@@ -49,21 +49,29 @@ Examples:
 EOF
 }
 
-_error() {
+curl() {
+  command "$CURL_EXEC" "$@"
+}
+
+error() {
   [ $# -gt 0 ] && echo >&2 "$PROGRAM:" "$@"
   echo >&2 "Try '$PROGRAM --help' for more information."
   exit 1
 }
 
-_make_error() {
+jq() {
+  command "$JQ_EXEC" "$@"
+}
+
+make_error() {
   # shellcheck disable=SC2016
-  "$JQ_EXEC" -cn --arg _ "$*" '{"errors":[{"reason":$_}]}'
+  jq -cn --arg reason "$*" '{ "errors": [ { "reason": $reason } ] }'
 }
 
 opts="$(
   getopt -n "$PROGRAM" -o k:p:b:f:m:h \
     -l token:,path:,body:,filter:,method:,prefix:,help -- "$@"
-)" || _error
+)" || error
 # shellcheck disable=SC2086
 eval set -- $opts
 
@@ -100,16 +108,16 @@ while [ $# -gt 0 ]; do
     ;;
   --) ;;
   *)
-    _error "unexpected argument '$ARG'"
+    error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "$LINODE_API_TOKEN" ] && _error "missing TOKEN"
-[ -z "$LINODE_API_PATH" ] && _error "missing PATH"
+[ -z "$LINODE_API_TOKEN" ] && error "missing TOKEN"
+[ -z "$LINODE_API_PATH" ] && error "missing PATH"
 
-which "$CURL_EXEC" >/dev/null || _error "curl not installed"
-which jq >/dev/null || _error "jq not installed"
+which "$CURL_EXEC" >/dev/null || error "curl not found"
+which "$JQ_EXEC" >/dev/null || error "jq not found"
 
 tmp_output="$(mktemp)"
 tmp_stderr="$(mktemp)"
@@ -123,23 +131,24 @@ set -- "-sS" "-o" "$tmp_output" \
 [ -n "$LINODE_API_BODY" ] && set -- "$@" -d "$LINODE_API_BODY"
 [ -n "$LINODE_API_FILTER" ] && set -- "$@" -H "X-Filter: $LINODE_API_FILTER"
 [ -n "$LINODE_API_METHOD" ] && set -- "$@" -X "$LINODE_API_METHOD"
+set -- "$@" "${LINODE_API_PREFIX}${LINODE_API_PATH}"
 
 set +e
-"$CURL_EXEC" "$@" "${LINODE_API_PREFIX}${LINODE_API_PATH}" 2>"$tmp_stderr"
+curl "$@" 2>"$tmp_stderr"
 result=$?
 set -e
 
 if [ $result != 0 ]; then
   if [ -s "$tmp_stderr" ]; then
-    _make_error "$(cat "$tmp_stderr")"
+    make_error "$(cat "$tmp_stderr")"
   else
-    _make_error "Unknown error"
+    make_error "Unknown error"
   fi
 else
   if [ -s "$tmp_output" ]; then
     cat "$tmp_output"
   else
-    _make_error "No data"
+    make_error "No data"
   fi
 fi
 
diff --git a/bin/linode-create b/bin/linode-create
--- a/bin/linode-create
+++ b/bin/linode-create
@@ -44,20 +44,32 @@ Enviroment variable mappings:
 EOF
 }
 
-_error() {
+error() {
   [ $# -gt 0 ] && echo >&2 "$PROGRAM:" "$@"
   echo >&2 "Try '$PROGRAM --help' for more information."
   exit 1
 }
 
-_out() {
+jq() {
+  command "$JQ_EXEC" "$@"
+}
+
+linode_api() {
+  command "$LINODE_API_EXEC" "$@"
+}
+
+linode_query() {
+  command "$LINODE_QUERY_EXEC" "$@"
+}
+
+out() {
   [ -n "$QUIET" ] || echo "$@"
 }
 
 opts="$(
   getopt -n "$PROGRAM" -o k:l:i:r:t:o:qh \
     -l token:,label:,image:,region:,type:,output:,quiet,help -- "$@"
-)" || _error
+)" || error
 # shellcheck disable=SC2086
 eval set -- $opts
 
@@ -98,16 +110,18 @@ while [ $# -gt 0 ]; do
     ;;
   --) ;;
   *)
-    _error "unexpected argument '$ARG'"
+    error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "${LINODE_API_TOKEN:-}" ] && _error "missing TOKEN"
-[ -z "${LINODE_LABEL:-}" ] && _error "missing LABEL"
+[ -z "${LINODE_API_TOKEN:-}" ] && error "missing TOKEN"
+[ -z "${LINODE_LABEL:-}" ] && error "missing LABEL"
 
-which "$JQ_EXEC" >/dev/null || _error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || _error "linode-api not installed"
+which "$JQ_EXEC" >/dev/null || error "jq not installed"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
+
+export LINODE_API_TOKEN
 
 if [ -n "$QUIET" ]; then
   QUIET_ARG=-q
@@ -119,16 +133,14 @@ tmp="$(mktemp)"
 
 trap 'rm -f -- "$tmp"' EXIT
 
-export LINODE_API_TOKEN
-
 set +e
 # shellcheck disable=SC2086
-"$LINODE_QUERY_EXEC" -l "$LINODE_LABEL" -o "$tmp" $QUIET_ARG
+linode_query -l "$LINODE_LABEL" -o "$tmp" $QUIET_ARG
 exitcode=$?
 set -e
 
 if [ $exitcode = 0 ] || ! grep -q "^LINODE_API_ERROR='Not found'$" "$tmp"; then
-  [ $exitcode = 0 ] && _out "Create: no"
+  [ $exitcode = 0 ] && out "Create: no"
   if [ -n "$OUTPUT_PATH" ]; then
     cat "$tmp" >"$OUTPUT_PATH"
     echo "LINODE_CREATE='no'" >>"$OUTPUT_PATH"
@@ -136,9 +148,9 @@ if [ $exitcode = 0 ] || ! grep -q "^LINODE_API_ERROR='Not found'$" "$tmp"; then
   exit $exitcode
 fi
 
-_out -n "Querying SSH keys..."
+out -n "Querying SSH keys..."
 
-"$LINODE_API_EXEC" -p /profile/sshkeys >"$tmp"
+linode_api -p /profile/sshkeys >"$tmp"
 
 # shellcheck disable=SC2016
 keys_filter='@sh "LINODE_API_STATUS=\("error")
@@ -153,17 +165,17 @@ LINODE_REGION=\("")
 LINODE_TYPE=\("")
 LINODE_CREATE=\("no")"'
 
-output="$("$JQ_EXEC" -r --arg label_ "$LINODE_LABEL" "$keys_filter" "$tmp")"
+output="$(jq -r --arg label_ "$LINODE_LABEL" "$keys_filter" "$tmp")"
 
 if echo "$output" | grep -q "LINODE_API_ERROR=''"; then
-  _out ok
+  out ok
 else
-  _out error
+  out error
   [ -n "$OUTPUT_PATH" ] && echo "$output" >"$OUTPUT_PATH"
   exit 1
 fi
 
-_out -n "Creating instance $LINODE_LABEL..."
+out -n "Creating instance $LINODE_LABEL..."
 
 authorized_keys_json="$(jq -c '[ .data // [] | .[].ssh_key ]' "$tmp")"
 
@@ -171,7 +183,7 @@ root_pass="$(tr -cd '[:graph:]' </dev/urandom | head -c 20)"
 
 # shellcheck disable=SC2016
 body="$(
-  "$JQ_EXEC" -cn \
+  jq -cn \
     --argjson authorized_keys "$authorized_keys_json" \
     --arg label_ "$LINODE_LABEL" \
     --arg image "$LINODE_IMAGE" \
@@ -188,7 +200,7 @@ body="$(
     }'
 )"
 
-"$LINODE_API_EXEC" -m POST -p /linode/instances -b "$body" >"$tmp"
+linode_api -m POST -b "$body" -p /linode/instances >"$tmp"
 
 # shellcheck disable=SC2016
 create_filter='@sh "LINODE_API_STATUS=\(
@@ -204,33 +216,33 @@ LINODE_REGION=\(.region // "")
 LINODE_TYPE=\(.type // "")
 LINODE_CREATE=\(if .id then "yes" else "no" end)"'
 
-output="$("$JQ_EXEC" --arg label_ "$LINODE_LABEL" -r "$create_filter" "$tmp")"
+output="$(jq --arg label_ "$LINODE_LABEL" -r "$create_filter" "$tmp")"
 
 eval "$output"
 
 if [ "$LINODE_API_STATUS" = error ]; then
-  _out error
-  _out "Error: $LINODE_API_ERROR"
+  out error
+  out "Error: $LINODE_API_ERROR"
   exitcode=1
 elif [ -z "$LINODE_ID" ]; then
-  _out error
-  _out "Error: No Linode ID"
+  out error
+  out "Error: No Linode ID"
   output="$(echo "$output" |
     sed "s/^LINODE_API_STATUS.*\$/LINODE_API_STATUS='error'/" |
     sed "s/^LINODE_API_ERROR.*\$/LINODE_API_ERROR='No Linode ID'/")"
   exitcode=1
 else
-  _out ok
-  _out
-  _out " Label: $LINODE_LABEL"
-  _out "    ID: $LINODE_ID"
-  _out "Status: $LINODE_STATUS"
-  _out "  IPV4: $LINODE_IPV4"
-  _out "  IPV6: $LINODE_IPV6"
-  _out "Region: $LINODE_REGION"
-  _out " Image: $LINODE_IMAGE"
-  _out "  Type: $LINODE_TYPE"
-  _out "Create: yes"
+  out ok
+  out
+  out " Label: $LINODE_LABEL"
+  out "    ID: $LINODE_ID"
+  out "Status: $LINODE_STATUS"
+  out "  IPV4: $LINODE_IPV4"
+  out "  IPV6: $LINODE_IPV6"
+  out "Region: $LINODE_REGION"
+  out " Image: $LINODE_IMAGE"
+  out "  Type: $LINODE_TYPE"
+  out "Create: yes"
   exitcode=0
 fi
 
diff --git a/bin/linode-delete b/bin/linode-delete
--- a/bin/linode-delete
+++ b/bin/linode-delete
@@ -35,20 +35,32 @@ Enviroment variable mappings:
 EOF
 }
 
-_error() {
+error() {
   [ $# -gt 0 ] && echo >&2 "$PROGRAM:" "$@"
   echo >&2 "Try '$PROGRAM --help' for more information."
   exit 1
 }
 
-_out() {
+jq() {
+  command "$JQ_EXEC" "$@"
+}
+
+linode_api() {
+  command "$LINODE_API_EXEC" "$@"
+}
+
+linode_query() {
+  command "$LINODE_QUERY_EXEC" "$@"
+}
+
+out() {
   [ -n "$QUIET" ] || echo "$@"
 }
 
 opts="$(
   getopt -n "$PROGRAM" -o k:l:o:qh \
     -l token:,label:,output:,quiet,help -- "$@"
-)" || _error
+)" || error
 # shellcheck disable=SC2086
 eval set -- $opts
 
@@ -77,16 +89,18 @@ while [ $# -gt 0 ]; do
     ;;
   --) ;;
   *)
-    _error "unexpected argument '$ARG'"
+    error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "${LINODE_API_TOKEN:-}" ] && _error "missing TOKEN"
-[ -z "${LINODE_LABEL:-}" ] && _error "missing LABEL"
+[ -z "${LINODE_API_TOKEN:-}" ] && error "missing TOKEN"
+[ -z "${LINODE_LABEL:-}" ] && error "missing LABEL"
 
-which "$JQ_EXEC" >/dev/null || _error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || _error "linode-api not installed"
+which "$JQ_EXEC" >/dev/null || error "jq not installed"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
+
+export LINODE_API_TOKEN
 
 if [ -n "$QUIET" ]; then
   QUIET_ARG=-q
@@ -98,11 +112,9 @@ tmp="$(mktemp)"
 
 trap 'rm -f -- "$tmp"' EXIT
 
-export LINODE_API_TOKEN
-
 set +e
 # shellcheck disable=SC2086
-"$LINODE_QUERY_EXEC" -l "$LINODE_LABEL" -o "$tmp" $QUIET_ARG
+linode_query -l "$LINODE_LABEL" -o "$tmp" $QUIET_ARG
 exitcode=$?
 set -e
 
@@ -117,10 +129,10 @@ fi
 # shellcheck disable=SC1090
 . "$tmp"
 
-_out
-_out -n "Deleting instance $LINODE_LABEL..."
+out
+out -n "Deleting instance $LINODE_LABEL..."
 
-"$LINODE_API_EXEC" -m DELETE -p "/linode/instances/$LINODE_ID" >"$tmp"
+linode_api -m DELETE -p "/linode/instances/$LINODE_ID" >"$tmp"
 
 # shellcheck disable=SC2016
 delete_filter='@sh "LINODE_API_STATUS=\(
@@ -130,21 +142,21 @@ LINODE_LABEL=\($label_)
 LINODE_ID=\($id)
 LINODE_DELETE=\(if .errors[0].reason then "no" else "yes" end)"'
 
-output="$("$JQ_EXEC" --arg label_ "$LINODE_LABEL" --arg id "$LINODE_ID" \
+output="$(jq --arg label_ "$LINODE_LABEL" --arg id "$LINODE_ID" \
   -r "$delete_filter" "$tmp")"
 
 eval "$output"
 
 if [ "$LINODE_API_STATUS" = error ]; then
-  _out error
-  _out "Error: $LINODE_API_ERROR"
+  out error
+  out "Error: $LINODE_API_ERROR"
   exitcode=1
 else
-  _out ok
-  _out
-  _out " Label: $LINODE_LABEL"
-  _out "    ID: $LINODE_ID"
-  _out "Delete: yes"
+  out ok
+  out
+  out " Label: $LINODE_LABEL"
+  out "    ID: $LINODE_ID"
+  out "Delete: yes"
   exitcode=0
 fi
 
diff --git a/bin/linode-dns b/bin/linode-dns
--- a/bin/linode-dns
+++ b/bin/linode-dns
@@ -15,21 +15,24 @@ LINODE_API_EXEC="${LINODE_API_EXEC:-linode-api}"
 
 usage() {
   cat <<EOF
-Usage: $PROGRAM [OPTIONS] -k TOKEN -d DOMAIN [ -n NAME ] [ -4 IPv4 ] [ -6 IPV6 ]
+Usage: $PROGRAM [OPTIONS] -k TOKEN -d DOMAIN [ -n NAME ] [ -4 IPV4 ] [ -6 IPV6 ]
 
-Set IPv4/6 records on Linode domains.
+Set A (IPv4), AAAA (IPv6) Linode domain records.
 
-If -4 and -6 are not specified, then this does not modify anything.
+If -n is not specified or blank, then this will show/modify the root records.
 
-If a single dot '.' is passed to -4 / -6, then the respective records are
-deleted.
+If both -4 and -6 are not specified or blank, then this will just show the
+current records.
+
+If a single dot '.' is the argument for -4 / -6, then the respective records
+are deleted.
 
 Required arguments:
   -k, --token=TOKEN      Linode API token
   -d, --domain=DOMAIN    Linode domain
-  -n, --name=NAME        Record name
-  -4, --ipv4=IPV4        Record target IPv4 address
-  -6, --ipv6=IPV6        Record target IPv6 address
+  -n, --name=NAME        Linode domain record name
+  -4, --ipv4=IPV4        Set target IPv4 address
+  -6, --ipv6=IPV6        Set target IPv6 address
 
 Optional arguments:
   -t, --ttl=TTL          Time-to-live (TTL) in seconds
@@ -37,29 +40,52 @@ Optional arguments:
   -h, --help             This help text
 
 Enviroment variable mappings:
-  LINODE_API_TOKEN     --token
-  CURL_EXEC            Path to curl
-  JQ_EXEC              Path to jq
-  LINODE_API_EXEC      Path to linode-api
+  LINODE_API_TOKEN       --token
+  CURL_EXEC              Path to curl
+  JQ_EXEC                Path to jq
+  LINODE_API_EXEC        Path to linode-api
 
-LIMITATION: this does not work with domains with +100 records (TODO).
+LIMITATION: This only works with A and AAAA records with a single target.
 EOF
 }
 
-_error() {
+error() {
   [ $# -gt 0 ] && echo >&2 "$PROGRAM:" "$@"
   echo >&2 "Try '$PROGRAM --help' for more information."
   exit 1
 }
 
-_out() {
+jq() {
+  command "$JQ_EXEC" "$@"
+}
+
+linode_api() {
+  command "$LINODE_API_EXEC" "$@"
+}
+
+linode_api_with_check() {
+  out -n "$1..."
+  shift
+  LINODE_API_OUTPUT="$(linode_api "$@")"
+  LINODE_API_ERROR="$(echo "$LINODE_API_OUTPUT" |
+    jq -r '.errors[0].reason // ""')"
+  if [ -z "$LINODE_API_ERROR" ]; then
+    out ok
+  else
+    out error
+    out "Error: $LINODE_API_ERROR"
+    exit 1
+  fi
+}
+
+out() {
   [ -n "$QUIET" ] || echo "$@"
 }
 
 opts="$(
   getopt -n "$PROGRAM" -o k:d:n:4:6:t:h \
     -l token:,domain:,name:,ipv4:,ipv6:,ttl:,help -- "$@"
-)" || _error
+)" || error
 # shellcheck disable=SC2086
 eval set -- $opts
 
@@ -101,51 +127,35 @@ while [ $# -gt 0 ]; do
     ;;
   --) ;;
   *)
-    _error "unexpected argument '$ARG'"
+    error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "$LINODE_API_TOKEN" ] && _error "missing TOKEN"
-[ -z "$LINODE_DOMAIN" ] && _error "missing DOMAIN"
+[ -z "$LINODE_API_TOKEN" ] && error "missing TOKEN"
+[ -z "$LINODE_DOMAIN" ] && error "missing DOMAIN"
 
-export LINODE_API_TOKEN
+which "$JQ_EXEC" >/dev/null || error "jq not installed"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
+
 if [ -n "$LINODE_RECORD_NAME" ]; then
   LINODE_RECORD_FQDN="$LINODE_RECORD_NAME.$LINODE_DOMAIN"
 else
   LINODE_RECORD_FQDN="$LINODE_DOMAIN"
 fi
 
-which "$JQ_EXEC" >/dev/null || _error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || _error "linode-api not installed"
+export LINODE_API_TOKEN
 
-tmp="$(mktemp)"
+domain_filter="$(jq -cn --arg domain "$LINODE_DOMAIN" \
+  "{ \"domain\": \$domain }")"
 
-trap 'rm -f -- "$tmp"' EXIT
+linode_api_with_check "Querying domain $LINODE_DOMAIN" \
+  -f "$domain_filter" -p /domains
 
-_out -n "Querying domain $LINODE_DOMAIN..."
-
-# shellcheck disable=SC2016
-domain_filter="$("$JQ_EXEC" -cn --arg domain "$LINODE_DOMAIN" \
-  '{ "domain": $domain }')"
-
-"$LINODE_API_EXEC" -p /domains -f "$domain_filter" >"$tmp"
-
-LINODE_DOMAIN_ID="$(jq -r '.data[0].id // ""' "$tmp")"
-LINODE_API_ERROR="$(jq -r '.errors[0].reason // ""' "$tmp")"
-
-if [ -n "$LINODE_DOMAIN_ID" ]; then
-  _out ok
-else
-  _out error
-  _out "Error: ${LINODE_API_ERROR:-Unknown}"
-  exit 1
-fi
-
-_out -n "Querying domain records..."
+LINODE_DOMAIN_ID="$(echo "$LINODE_API_OUTPUT" | jq -r '.data[0].id // ""')"
 
 # shellcheck disable=SC2016
-records_filter="$("$JQ_EXEC" -cn --arg name "$LINODE_RECORD_NAME" '{
+records_filter="$(jq -cn --arg name "$LINODE_RECORD_NAME" '{
   "+and": [
     { "name": $name },
     {
@@ -159,32 +169,24 @@ records_filter="$("$JQ_EXEC" -cn --arg name "$LINODE_RECORD_NAME" '{
   "+order_by": "name"
 }')"
 
-"$LINODE_API_EXEC" -p "/domains/$LINODE_DOMAIN_ID/records" \
-  -f "$records_filter" >"$tmp"
+linode_api_with_check "Querying domain records" \
+  -f "$records_filter" -p "/domains/$LINODE_DOMAIN_ID/records"
 
-LINODE_API_ERROR="$(jq -r '.errors[0].reason // ""' "$tmp")"
+out
 
-if [ -z "$LINODE_API_ERROR" ]; then
-  _out ok
-else
-  _out error
-  _out "Error: $LINODE_API_ERROR"
-  exit 1
-fi
+echo "$LINODE_API_OUTPUT" | jq -c '.data[]' | {
 
-_out
+  if [ -n "$LINODE_RECORD_TTL" ]; then
+    ttl_js=", \"ttl_sec\": \$ttl | tonumber"
+  else
+    ttl_js=
+  fi
 
-if [ -n "$LINODE_RECORD_TTL" ]; then
-  # shellcheck disable=SC2016
-  LINODE_RECORD_TTL_JS=', "ttl_sec": $ttl | tonumber'
-else
-  LINODE_RECORD_TTL_JS=
-fi
-
-"$JQ_EXEC" -c '.data[]' "$tmp" | {
+  count=0
 
   while read -r record_json; do
 
+    count=$((count + 1))
     id="$(echo "$record_json" | jq -r .id)"
     target="$(echo "$record_json" | jq -r .target)"
     type="$(echo "$record_json" | jq -r .type)"
@@ -195,54 +197,36 @@ fi
       new_target="$LINODE_RECORD_IPV6"
     fi
 
-    _out -n "$LINODE_RECORD_FQDN: $target ($type) "
+    out -n "$LINODE_RECORD_FQDN: $target ($type) "
 
     if [ -n "$new_target" ] && [ "$target" != "$new_target" ]; then
-
       if [ "$new_target" = . ]; then
-
-        _out -n "deleting..."
-        "$LINODE_API_EXEC" -m DELETE \
-          -p "/domains/$LINODE_DOMAIN_ID/records/$id" >/dev/null
-        _out "ok"
-        # TODO check for errors
-
+        linode_api_with_check deleting \
+          -m DELETE -p "/domains/$LINODE_DOMAIN_ID/records/$id"
       else
-
         body="$(
-          "$JQ_EXEC" -cn \
+          jq -cn \
             --arg target "$new_target" \
             --arg ttl "$LINODE_RECORD_TTL" \
             "{
-              \"target\": \$target
-              $LINODE_RECORD_TTL_JS
+              \"target\": \$target $ttl_js
             }"
         )"
-
-        _out -n "-> $new_target updating..."
-        "$LINODE_API_EXEC" -m PUT -b "$body" \
-          -p "/domains/$LINODE_DOMAIN_ID/records/$id" >/dev/null
-        _out "ok"
-        # TODO check for errors
-
-        if [ "$type" = A ]; then
-          LINODE_RECORD_IPV4=.
-        else
-          LINODE_RECORD_IPV6=.
-        fi
-
+        out -n "-> $new_target "
+        linode_api_with_check updating \
+          -m PUT -b "$body" -p "/domains/$LINODE_DOMAIN_ID/records/$id"
+        target="$new_target"
       fi
-
     else
+      out
+    fi
 
-      _out
-
+    if [ -n "$new_target" ] && [ "$target" = "$new_target" ]; then
       if [ "$type" = A ]; then
         LINODE_RECORD_IPV4=.
       else
         LINODE_RECORD_IPV6=.
       fi
-
     fi
   done
 
@@ -252,29 +236,29 @@ fi
     else
       target="$LINODE_RECORD_IPV6"
     fi
-    if [ -n "$target" ] && [ $target != . ]; then
 
-      # shellcheck disable=SC2016
+    if [ -n "$target" ] && [ $target != . ]; then
+      count=$((count + 1))
+      out -n "$LINODE_RECORD_FQDN: $target ($type) "
       body="$(
-        "$JQ_EXEC" -cn \
+        jq -cn \
           --arg type "$type" \
           --arg name "$LINODE_RECORD_NAME" \
           --arg target "$target" \
           --arg ttl "$LINODE_RECORD_TTL" "{
             \"type\": \$type,
             \"name\": \$name,
-            \"target\": \$target
-            $LINODE_RECORD_TTL_JS
+            \"target\": \$target $ttl_js
           }"
       )"
-
-      _out -n "$LINODE_RECORD_FQDN: $target ($type) creating..."
-      "$LINODE_API_EXEC" -m POST -b "$body" \
-        -p "/domains/$LINODE_DOMAIN_ID/records" >/dev/null
-      _out "ok"
-      # TODO check for errors
+      linode_api_with_check creating \
+        -m POST -b "$body" -p "/domains/$LINODE_DOMAIN_ID/records"
     fi
   done
+
+  if [ $count = 0 ]; then
+    out "No records."
+  fi
 }
 
 exit 0
diff --git a/bin/linode-list b/bin/linode-list
--- a/bin/linode-list
+++ b/bin/linode-list
@@ -29,16 +29,24 @@ LIMITATION: this will only show up to 100 Linodes.
 EOF
 }
 
-_error() {
+error() {
   [ $# -gt 0 ] && echo >&2 "$PROGRAM:" "$@"
   echo >&2 "Try '$PROGRAM --help' for more information."
   exit 1
 }
 
+jq() {
+  command "$JQ_EXEC" "$@"
+}
+
+linode_api() {
+  command "$LINODE_API_EXEC" "$@"
+}
+
 opts="$(
   getopt -n "$PROGRAM" -o k:h \
     -l token:,help -- "$@"
-)" || _error
+)" || error
 # shellcheck disable=SC2086
 eval set -- $opts
 
@@ -56,35 +64,31 @@ while [ $# -gt 0 ]; do
     ;;
   --) ;;
   *)
-    _error "unexpected argument '$ARG'"
+    error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "${LINODE_API_TOKEN:-}" ] && _error "missing TOKEN"
+[ -z "${LINODE_API_TOKEN:-}" ] && error "missing TOKEN"
+
+which "$JQ_EXEC" >/dev/null || error "jq not found"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not found"
 
 export LINODE_API_TOKEN
 
-which "$JQ_EXEC" >/dev/null || _error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || _error "linode-api not installed"
-
-tmp="$(mktemp)"
-
-trap 'rm -f -- "$tmp"' EXIT
-
 linode_filter='{"+order": "asc", "+order_by": "label"}'
 
-"$LINODE_API_EXEC" -p /linode/instances -f "$linode_filter" >"$tmp"
+output="$(linode_api -p /linode/instances -f "$linode_filter")"
 
-LINODE_API_ERROR="$("$JQ_EXEC" -r '.errors[0].reason // ""' "$tmp")"
+linode_api_error="$(echo "$output" | jq -r '.errors[0].reason // ""')"
 
-if [ -z "$LINODE_API_ERROR" ]; then
+if [ -z "$linode_api_error" ]; then
   filter='.data[] | @text
   "\(.label)\t\(.id)\t\(.ipv4[0])\t\(.ipv6 | sub("/.+$"; ""))\t\(.region)\t\(.status)"'
-  "$JQ_EXEC" -r "$filter" "$tmp" |
+  echo "$output" | jq -r "$filter" |
     column -t -s "$(printf '\t')" -N Label,ID,IPv4,IPv6,Region,Status -o ' | '
   exit 0
 else
-  echo >&2 "Error: $LINODE_API_ERROR"
+  echo >&2 "Error: $linode_api_error"
   exit 1
 fi
diff --git a/bin/linode-query b/bin/linode-query
--- a/bin/linode-query
+++ b/bin/linode-query
@@ -33,20 +33,28 @@ Enviroment variable mappings:
 EOF
 }
 
-_error() {
+error() {
   [ $# -gt 0 ] && echo >&2 "$PROGRAM:" "$@"
   echo >&2 "Try '$PROGRAM --help' for more information."
   exit 1
 }
 
-_out() {
+jq() {
+  command "$JQ_EXEC" "$@"
+}
+
+linode_api() {
+  command "$LINODE_API_EXEC" "$@"
+}
+
+out() {
   [ -n "$QUIET" ] || echo "$@"
 }
 
 opts="$(
   getopt -n "$PROGRAM" -o k:l:o:qh \
     -l token:,label:,output:,quiet,help -- "$@"
-)" || _error
+)" || error
 # shellcheck disable=SC2086
 eval set -- $opts
 
@@ -75,29 +83,24 @@ while [ $# -gt 0 ]; do
     ;;
   --) ;;
   *)
-    _error "unexpected argument '$ARG'"
+    error "unexpected argument '$ARG'"
     ;;
   esac
 done
 
-[ -z "${LINODE_API_TOKEN:-}" ] && _error "missing TOKEN"
-[ -z "${LINODE_LABEL:-}" ] && _error "missing LABEL"
+[ -z "${LINODE_API_TOKEN:-}" ] && error "missing TOKEN"
+[ -z "${LINODE_LABEL:-}" ] && error "missing LABEL"
+
+which "$JQ_EXEC" >/dev/null || error "jq not installed"
+which "$LINODE_API_EXEC" >/dev/null || error "linode-api not installed"
 
 export LINODE_API_TOKEN
 
-which "$JQ_EXEC" >/dev/null || _error "jq not installed"
-which "$LINODE_API_EXEC" >/dev/null || _error "linode-api not installed"
+out -n "Querying instance $LINODE_LABEL..."
 
-tmp="$(mktemp)"
+linode_filter="$(jq -cn --arg label_ "$LINODE_LABEL" '{ "label": $label_ }')"
 
-trap 'rm -f -- "$tmp"' EXIT
-
-_out -n "Querying instance $LINODE_LABEL..."
-
-# shellcheck disable=SC2016
-linode_filter="$("$JQ_EXEC" -cn --arg _ "$LINODE_LABEL" '{ "label": $_ }')"
-
-"$LINODE_API_EXEC" -p /linode/instances -f "$linode_filter" >"$tmp"
+json="$(linode_api -f "$linode_filter" -p /linode/instances)"
 
 # shellcheck disable=SC2016
 query_filter='@sh "LINODE_API_STATUS=\(
@@ -112,31 +115,31 @@ LINODE_IMAGE=\(.data[0].image // "")
 LINODE_REGION=\(.data[0].region // "")
 LINODE_TYPE=\(.data[0].type // "")"'
 
-output="$("$JQ_EXEC" -r --arg label_ "$LINODE_LABEL" "$query_filter" "$tmp")"
+output="$(echo "$json" | jq -r --arg label_ "$LINODE_LABEL" "$query_filter")"
 
 eval "$output"
 
 if [ "$LINODE_API_STATUS" = error ]; then
-  _out error
-  _out "Error: $LINODE_API_ERROR"
+  out error
+  out "Error: $LINODE_API_ERROR"
   exitcode=1
 elif [ -z "$LINODE_ID" ]; then
-  _out not found
+  out not found
   output="$(echo "$output" |
     sed "s/^LINODE_API_STATUS.*\$/LINODE_API_STATUS='error'/" |
     sed "s/^LINODE_API_ERROR.*\$/LINODE_API_ERROR='Not found'/")"
   exitcode=1
 else
-  _out ok
-  _out
-  _out " Label: $LINODE_LABEL"
-  _out "    ID: $LINODE_ID"
-  _out "Status: $LINODE_STATUS"
-  _out "  IPV4: $LINODE_IPV4"
-  _out "  IPV6: $LINODE_IPV6"
-  _out "Region: $LINODE_REGION"
-  _out " Image: $LINODE_IMAGE"
-  _out "  Type: $LINODE_TYPE"
+  out ok
+  out
+  out " Label: $LINODE_LABEL"
+  out "    ID: $LINODE_ID"
+  out "Status: $LINODE_STATUS"
+  out "  IPV4: $LINODE_IPV4"
+  out "  IPV6: $LINODE_IPV6"
+  out "Region: $LINODE_REGION"
+  out " Image: $LINODE_IMAGE"
+  out "  Type: $LINODE_TYPE"
   exitcode=0
 fi
 
